interface Transaction {
  id: string;
  from_account: string;
  to_account: string;
  amount: number;
  description: string | null;
  timestamp: string;
}

interface StatementData {
  accountNumber: string;
  accountName: string;
  balance: number;
  transactions: Transaction[];
  generatedAt: string;
}

export function generateCSV(data: StatementData): string {
  const lines: string[] = [];
  
  // Header
  lines.push('MINI BANK - ACCOUNT STATEMENT');
  lines.push('');
  lines.push(`Generated:,${data.generatedAt}`);
  lines.push(`Account:,${data.accountNumber}`);
  lines.push(`Name:,${data.accountName}`);
  lines.push(`Current Balance:,NPR ${data.balance.toLocaleString()}`);
  lines.push('');
  
  // Column headers
  lines.push('Date,Time,Type,Account,Amount,Description');
  
  // Transactions
  data.transactions.forEach(txn => {
    const date = new Date(txn.timestamp);
    const isSent = txn.from_account === data.accountNumber;
    const otherAccount = isSent ? txn.to_account : txn.from_account;
    const type = isSent ? 'SENT' : 'RECEIVED';
    
    lines.push(
      `${date.toLocaleDateString()},${date.toLocaleTimeString()},${type},${otherAccount},${isSent ? '-' : '+'}NPR ${txn.amount},${txn.description || ''}`
    );
  });
  
  return lines.join('\n');
}

export function generateMarkdownReport(data: StatementData): string {
  let md = `# Mini Bank - Account Statement\n\n`;
  md += `**Generated:** ${data.generatedAt}\n\n`;
  md += `## Account Details\n\n`;
  md += `| Field | Value |\n`;
  md += `|-------|-------|\n`;
  md += `| Account | ${data.accountNumber} |\n`;
  md += `| Name | ${data.accountName} |\n`;
  md += `| Balance | NPR ${data.balance.toLocaleString()} |\n\n`;
  md += `## Transactions\n\n`;
  md += `| Date | Type | Account | Amount | Description |\n`;
  md += `|------|------|---------|--------|-------------|\n`;
  
  data.transactions.forEach(txn => {
    const date = new Date(txn.timestamp).toLocaleDateString();
    const isSent = txn.from_account === data.accountNumber;
    const otherAccount = isSent ? txn.to_account : txn.from_account;
    const type = isSent ? '🔴 Sent' : '🟢 Received';
    const amount = isSent ? `-NPR ${txn.amount}` : `+NPR ${txn.amount}`;
    
    md += `| ${date} | ${type} | ${otherAccount} | ${amount} | ${txn.description || '-'} |\n`;
  });
  
  md += `\n---\n*Generated by Mini Bank - Push. Deploy. Automate.*`;
  
  return md;
}