import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Transaction {
  id: string;
  from_account: string;
  to_account: string;
  amount: number;
  description: string | null;
  timestamp: string;
}

interface ReceiptData {
  transaction: Transaction;
  fromName: string;
  toName: string;
  fromAccount: string;
  toAccount: string;
  balanceAfter: number;
}

export function generateReceiptPDF(data: ReceiptData): string {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(13, 148, 136); // teal-600
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('🏦 Mini Bank', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Transaction Receipt', pageWidth / 2, 32, { align: 'center' });

  // Transaction details
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(11);
  
  const startY = 55;
  const leftCol = 20;
  const rightCol = 120;

  // Transaction ID
  doc.setFont('helvetica', 'bold');
  doc.text('Transaction ID:', leftCol, startY);
  doc.setFont('helvetica', 'normal');
  doc.text(data.transaction.id, rightCol, startY);

  // Date
  doc.setFont('helvetica', 'bold');
  doc.text('Date:', leftCol, startY + 10);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date(data.transaction.timestamp).toLocaleString(), rightCol, startY + 10);

  // From Account
  doc.setFont('helvetica', 'bold');
  doc.text('From:', leftCol, startY + 20);
  doc.setFont('helvetica', 'normal');
  doc.text(`${data.fromName} (${data.fromAccount})`, rightCol, startY + 20);

  // To Account  
  doc.setFont('helvetica', 'bold');
  doc.text('To:', leftCol, startY + 30);
  doc.setFont('helvetica', 'normal');
  doc.text(`${data.toName} (${data.toAccount})`, rightCol, startY + 30);

  // Amount
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Amount:', leftCol, startY + 45);
  doc.setTextColor(5, 150, 105); // emerald-600
  doc.text(`NPR ${data.transaction.amount.toLocaleString()}`, rightCol, startY + 45);

  // Description
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Description:', leftCol, startY + 60);
  doc.setFont('helvetica', 'normal');
  doc.text(data.transaction.description || 'Transfer', rightCol, startY + 60);

  // Balance After
  doc.setFont('helvetica', 'bold');
  doc.text('Balance After:', leftCol, startY + 75);
  doc.setFont('helvetica', 'normal');
  doc.text(`NPR ${data.balanceAfter.toLocaleString()}`, rightCol, startY + 75);

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('Generated by Mini Bank - Push. Deploy. Automate.', pageWidth / 2, 270, { align: 'center' });
  doc.text(`Transaction ID: ${data.transaction.id}`, pageWidth / 2, 277, { align: 'center' });

  // Return base64 PDF
  return doc.output('datauristring');
}