/**
 * Daily Transaction Report Generator
 * Sends individual PDF report to each account holder
 */

const https = require('https');
const PDFDocument = require('pdfkit');

const config = {
  cloudflareApiToken: process.env.CLOUDFLARE_API_TOKEN,
  cloudflareAccountId: process.env.CLOUDFLARE_ACCOUNT_ID,
  d1DatabaseId: process.env.D1_DATABASE_ID,
  resendApiKey: process.env.RESEND_API_KEY,
};

function makeRequest(options, body = null) {
  return new Promise((resolve, reject) => {
    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => (data += chunk));
      res.on('end', () => {
        try { resolve({ status: res.statusCode, data: JSON.parse(data) }); }
        catch (e) { resolve({ status: res.statusCode, data }); }
      });
    });
    req.on('error', reject);
    if (body) req.write(body);
    req.end();
  });
}

async function queryD1(sql, params = []) {
  const options = {
    hostname: 'api.cloudflare.com',
    path: `/client/v4/accounts/${config.cloudflareAccountId}/d1/database/${config.d1DatabaseId}/query`,
    method: 'POST',
    headers: { 'Authorization': `Bearer ${config.cloudflareApiToken}`, 'Content-Type': 'application/json' },
  };
  const response = await makeRequest(options, JSON.stringify({ sql, params }));
  if (response.status !== 200 || !response.data.success) throw new Error('D1 query failed');
  return response.data.result[0].results;
}

async function getAllAccounts() {
  return queryD1('SELECT * FROM accounts WHERE is_active = 1');
}

async function getDailyTransactions(email) {
  return queryD1(
    `SELECT * FROM transactions WHERE (from_email = ? OR to_email = ?) AND created_at >= datetime('now', '-1 day') ORDER BY created_at DESC`,
    [email, email]
  );
}

function generatePDF(account, transactions) {
  return new Promise((resolve) => {
    const chunks = [];
    const doc = new PDFDocument({ margin: 50 });
    
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    
    // Header
    doc.fontSize(20).text('Mini Bank', { align: 'center' });
    doc.fontSize(14).text('Daily Transaction Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.moveDown(2);
    
    // Account Info
    doc.fontSize(12).text(`Name: ${account.name}`);
    doc.text(`Email: ${account.email}`);
    doc.text(`Current Balance: Rs. ${account.balance || 0}`);
    doc.moveDown(2);
    
    // Transactions
    doc.fontSize(14).text('Transactions Today:', { underline: true });
    doc.moveDown();
    
    if (transactions.length === 0) {
      doc.fontSize(12).text('No transactions today.');
    } else {
      doc.fontSize(10);
      doc.text('Date/Time'.padEnd(25) + 'Type'.padEnd(15) + 'Amount'.padEnd(15) + 'Details');
      doc.text('-'.repeat(70));
      
      let totalIn = 0, totalOut = 0;
      transactions.forEach(t => {
        const isOut = t.from_email === account.email;
        const amount = parseFloat(t.amount);
        if (isOut) totalOut += amount;
        else totalIn += amount;
        
        const dir = isOut ? '→ SENT' : '← RECEIVED';
        const line = `${t.created_at}`.substring(0, 19).padEnd(25) + 
                     (t.type || 'transfer').padEnd(15) + 
                     `${isOut ? '-' : '+'}Rs. ${t.amount}`.padEnd(15) + 
                     dir;
        doc.text(line);
        if (!isOut) {
          doc.text(`    From: ${t.from_email}`);
        } else {
          doc.text(`    To: ${t.to_email}`);
        }
      });
      
      doc.moveDown();
      doc.text('-'.repeat(70));
      doc.text(`Total Received: Rs. ${totalIn}`);
      doc.text(`Total Sent: Rs. ${totalOut}`);
    }
    
    doc.moveDown(2);
    doc.fontSize(10).text('Generated by Mini Bank App', { align: 'center' });
    
    doc.end();
  });
}

async function sendEmail(to, pdfBuffer, accountName) {
  if (!config.resendApiKey) {
    console.log(`No Resend key - skipping email to ${to}`);
    return;
  }
  
  const pdfBase64 = pdfBuffer.toString('base64');
  
  const res = await makeRequest({
    hostname: 'api.resend.com',
    path: '/emails',
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${config.resendApiKey}`,
      'Content-Type': 'application/json'
    },
  }, JSON.stringify({
    from: 'Mini Bank <onboarding@resend.dev>',
    to: to,
    subject: `Daily Report - ${new Date().toLocaleDateString()}`,
    text: `Hi ${accountName}, attached is your daily transaction report from Mini Bank.`,
    attachments: [
      {
        filename: `report-${new Date().toISOString().split('T')[0]}.pdf`,
        content: pdfBase64
      }
    ]
  }));
  
  if (res.status !== 200) {
    console.log(`Email failed for ${to}:`, res.data);
    throw new Error('Email failed');
  }
}

async function main() {
  if (!config.cloudflareApiToken || !config.cloudflareAccountId || !config.d1DatabaseId) {
    console.log('Missing Cloudflare config - skipping');
    return;
  }
  
  console.log('Generating reports...');
  try {
    const accounts = await getAllAccounts();
    console.log(`Found ${accounts.length} accounts`);
    
    for (const acc of accounts) {
      const txns = await getDailyTransactions(acc.email);
      console.log(`${acc.email}: ${txns.length} transactions`);
      
      const pdf = await generatePDF(acc, txns);
      await sendEmail(acc.email, pdf, acc.name);
      console.log(`Sent PDF to ${acc.email}`);
    }
  } catch (e) {
    console.log('Error:', e.message);
  }
  console.log('Done!');
}

main().catch(e => { console.error(e); process.exit(1); });